import { MonthTheme } from "@/types/calendar";

export const MONTH_THEMES: MonthTheme[] = [
    {
        id: 0,
        month: "January",
        shortMonth: "Jan",
        imagePath: "/images/jan.jpg",
        accent: "#2563EB",
        accentLight: "#EFF6FF",
        sceneName: "Alpine Ascent",
    },
    {
        id: 1,
        month: "February",
        shortMonth: "Feb",
        imagePath: "/images/feb.jpg",
        accent: "#9333EA",
        accentLight: "#FAF5FF",
        sceneName: "Frozen Stillness",
    },
    {
        id: 2,
        month: "March",
        shortMonth: "Mar",
        imagePath: "/images/mar.jpg",
        accent: "#16A34A",
        accentLight: "#F0FDF4",
        sceneName: "First Bloom",
    },
    {
        id: 3,
        month: "April",
        shortMonth: "Apr",
        imagePath: "/images/apr.jpg",
        accent: "#0891B2",
        accentLight: "#ECFEFF",
        sceneName: "Spring Rain",
    },
    {
        id: 4,
        month: "May",
        shortMonth: "May",
        imagePath: "/images/may.jpg",
        accent: "#65A30D",
        accentLight: "#F7FEE7",
        sceneName: "Meadow Hour",
    },
    {
        id: 5,
        month: "June",
        shortMonth: "Jun",
        imagePath: "/images/jun.jpg",
        accent: "#EA580C",
        accentLight: "#FFF7ED",
        sceneName: "Golden Solstice",
    },
    {
        id: 6,
        month: "July",
        shortMonth: "Jul",
        imagePath: "/images/jul.jpg",
        accent: "#DC2626",
        accentLight: "#FEF2F2",
        sceneName: "Peak Summer",
    },
    {
        id: 7,
        month: "August",
        shortMonth: "Aug",
        imagePath: "/images/aug.jpg",
        accent: "#D97706",
        accentLight: "#FFFBEB",
        sceneName: "Late Light",
    },
    {
        id: 8,
        month: "September",
        shortMonth: "Sep",
        imagePath: "/images/sep.jpg",
        accent: "#B45309",
        accentLight: "#FFFBEB",
        sceneName: "Amber Turn",
    },
    {
        id: 9,
        month: "October",
        shortMonth: "Oct",
        imagePath: "/images/oct.jpg",
        accent: "#C2410C",
        accentLight: "#FFF7ED",
        sceneName: "Forest Blaze",
    },
    {
        id: 10,
        month: "November",
        shortMonth: "Nov",
        imagePath: "/images/nov.jpg",
        accent: "#475569",
        accentLight: "#F8FAFC",
        sceneName: "Grey Quiet",
    },
    {
        id: 11,
        month: "December",
        shortMonth: "Dec",
        imagePath: "/images/dec.jpg",
        accent: "#0F172A",
        accentLight: "#F8FAFC",
        sceneName: "Year's End",
    },
];

export const WEEKDAYS = [
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun",
] as const;

export const NOTES_STORAGE_KEY = "wall-calendar-notes";
